#  docker-compose -f .docker/cms/drupal/docker-compose-drupal-mysql.yml -p drupal-mysql up -d
#  docker-compose -f .docker/cms/drupal/docker-compose-drupal-mysql.yml -p drupal-mysql down

# Drupal with mysql
#
# Access via "http://localhost:8080"
#
# During initial Drupal setup,
# Database type: MySql
# Database name: drupal_db
# Database username: drupal
# Database password: drupal
# ADVANCED OPTIONS; Database host: mysql

services:
  mysql:
    image: mysql:5.7
    ports:
      - "3307:3306"
    volumes:
      - "~/.docker-data/databases/mysql:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysqlRoot
      MYSQL_DATABASE: drupal_db
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
  
  drupal:
    depends_on:
      - mysql
    image: drupal:7.101
    ports:
      - "8080:80"
    volumes:
      - "~/.docker-data/drupal/modules:/var/www/html/modules"
      - "~/.docker-data/drupal/profiles:/var/www/html/profiles"
      - "~/.docker-data/drupal/themes:/var/www/html/themes"
      - "~/.docker-data/drupal/sites:/var/www/html/sites"
    restart: always
    environment:
      MYSQL_DATABASE: drupal_db
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_ROOT_PASSWORD: mysqlRoot
