#  docker-compose -f .docker/cms/drupal/docker-compose-drupal-mysql.yml -p drupal-mysql up -d
#  docker-compose -f .docker/cms/drupal/docker-compose-drupal-mysql.yml -p drupal-mysql down

# Run this compose file with volumes commented, then copy the source docker files from the container into the host,
# then uncomment the volumes and run again to persist data and custom modules/themes.
# rename sites\default\default.settings.php -> settings.php
# Download SimpleSAMLphp module from
# https://github.com/simplesamlphp/simplesamlphp/releases/tag/v1.17.4
# and place into 'sites/simplesamlphp'
# Download SimpleSAMLphp Auth Drupal module from
# https://www.drupal.org/project/simplesamlphp_auth/releases/7.x-1.3
# and place into 'modules/simplesamlphp_auth' Then enable from modules page in Drupal
#
# Drupal with mysql
#
# Access via "http://localhost:8080"
#
# During initial Drupal setup,
# Database type: MySql
# Database name: drupal_db
# Database username: drupal
# Database password: drupal
# ADVANCED OPTIONS; Database host: mysql

services:
  mysql:
    image: mysql:5.7
    ports:
      - "3307:3306"
    volumes:
      - "~/.docker-data/databases/mysql:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysqlRoot
      MYSQL_DATABASE: drupal_db
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
  
  drupal:
    depends_on:
      - mysql
    image: drupal:7.101
    ports:
      - "8080:80"
    volumes:
      - "~/.docker-data/drupal/modules:/var/www/html/modules"
      - "~/.docker-data/drupal/profiles:/var/www/html/profiles"
      - "~/.docker-data/drupal/sites:/var/www/html/sites"
      - "~/.docker-data/drupal/themes:/var/www/html/themes"
      - "~/.docker-data/drupal/var:/var/www/html/var"
    restart: always
    environment:
      MYSQL_DATABASE: drupal_db
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_ROOT_PASSWORD: mysqlRoot
      UPLOAD_LIMIT: 20M
      MEMORY_LIMIT: 128M
