#  docker-compose -f .docker/monitoring/docker-compose-jaeger.yml -p jaeger up -d
#  docker-compose -f .docker/monitoring/docker-compose-jaeger.yml -p jaeger down

# docker run --rm --name jaeger -p 16686:16686 -p 4317:4317 -p 4318:4318 -p 5778:5778 -p 9411:9411 jaegertracing/jaeger:2.7.0

networks:
  seq:
    driver: bridge
services:
  jaeger:
    container_name: jaeger
    image: jaegertracing/jaeger:2.7.0
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "5778:5778"
      - "9411:9411"
    restart: unless-stopped